export { default as Sidebar } from "./sidebar/Sidebar";
export { default as Success } from "./success/Success";
export { default as Error } from "./error/Error";
export { default as PagePagination } from "./pagination/Pagination";
export { default as EditCourse } from "./edit/EditCourse";
export { default as HomeAdmin } from "./home/HomeAdmin";
export { default as HomeStudent } from "./home/HomeStudent";
export { default as DeleteUser } from "./user/DeleteUser";
export { default as EditUser } from "./user/EditUser";
